backend/api/urls.py
from django.conf.urls import url
from rest_framework.authtoken import views as drf_views

urlpatterns = [
    url(r'^auth$', drf_views.obtain_auth_token, name='auth'),
]

backend/backend/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from django.core.urlresolvers import reverse_lazy
import django.contrib.auth
import ecocases

# Serializers define the API representation.


class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^ecocases/', include('ecocases.urls',
                               namespace='ecocases', app_name='ecocases')),
    url(r'^', include('api.urls', namespace='api', app_name='api')),
    # url(r'^', include(router.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^login/$', django.contrib.auth.views.login, {'template_name': 'login.html'},
        name='mysite_login'),
    url(r'^logout/$', django.contrib.auth.views.logout,
        {'next_page': reverse_lazy('ecocases:index')}, name='mysite_logout'),
    url(r'^signup/$', ecocases.views.signup, name='mysite_signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        ecocases.views.activate, name='registration_activate'),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/ecocases/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^create/$', views.CreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', views.UpdateView.as_view(),
        name='update'),  # /tweet/1/update
    url(r'^(?P<pk>\d+)/delete/$', views.DeleteView.as_view(),
        name='delete'),  # /tweet/1/update
    url(r'^(?P<id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^user/(?P<username>\w+)/$', views.profile, name='profile'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^mechanisms/$', views.mechanism_list, name='mechanism_list'),
    url(r'^upload/csv/$', views.upload_csv, name='upload_csv'),
    url(r'^upload/json/$', views.upload_json, name='upload_json'),
]

backend/ecocases/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.forms import TextInput, Textarea
from django.core.files.storage import FileSystemStorage
from tinymce import models as tinymce_models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django import template
from django.utils.timezone import now
from ecocases.variables import *

# Create your models here.

register = template.Library()
default_user = User.objects.get(username='admin')


def make_upload_path(instance, filename):
    file_root, file_ext = os.path.splitext(filename)
    dir


class EcoCase(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)

    title = models.CharField(max_length=200)

    promise = tinymce_models.HTMLField()
    usage = tinymce_models.HTMLField()
    organization = tinymce_models.HTMLField()
    economic_transaction = tinymce_models.HTMLField(default='')

    reference = models.CharField(max_length=100, blank=True, null=True)
    direct_environmental_gain = models.NullBooleanField(null=True)
    indirect_environmental_gain = models.NullBooleanField(null=True)
    attractiveness_price = models.NullBooleanField(null=True)
    proven_cas_or_project = models.CharField(
        max_length=20, choices=case_type_choices, default='project')

    image_urls = models.CharField(
        max_length=2000, default='',  blank=True, null=True)
    images = models.FileField(upload_to='ecocases/',  blank=True, null=True)

    timestamp = models.DateTimeField(default=now, null=True)

    def __str__(self):
        return self.title

    def image_url_list(self):
        if self.image_urls != None:
            return self.image_urls.split(';')
        else:
            return ""

    def first_image_url(self):
        if self.image_urls != None:
            return self.image_urls.split(';')[0]
        else:
            return ""

    def get_absolute_url(self):
        return reverse('ecocases:detail', args=[str(self.id)])

    def get_short_title(self):
        if len(self.title) < 60:
            return self.title
        else:
            return (self.title[:60] + '..')


class ESM(models.Model):
    ecocase = models.ForeignKey(EcoCase, on_delete=models.CASCADE)
    type = models.IntegerField(default=1)

    def __str__(self):
        return esm_dict[str(self.type)]

    def get_title(self):
        return esm_dict[str(self.type)]

    def get_vote_point_total(self):
        vote_point_total = 0
        for vote in self.vote_set.all():
            vote_point_total += vote.vote_point
        return vote_point_total

    def vote_point_options(self):
        return vote_point_options


class Vote(models.Model):
    esm = models.ForeignKey(ESM, on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, default=default_user.id)
    vote_point = models.IntegerField(
        default=0,
        validators=[MaxValueValidator(16), MinValueValidator(0)]
    )

    def __str__(self):
        return 'ESM' + str(self.esm.type) + '_' + str(self.user) + ':' + str(self.vote_point)

backend/ecocases/views.py
import os
import datetime
from django.utils.timezone import now
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.views.generic.edit import FormView
from django.template import loader
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.urls import reverse
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.sites.shortcuts import get_current_site

from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

from django.utils.decorators import method_decorator

from .models import EcoCase, ESM, Vote
from .forms import EcoCaseForm, LoginForm, SignupForm
from .mixins import FormUserNeededMixin, UserOwnerMixin
from ecocases.variables import *
import logging
import json

from pprint import pprint


uploaded_image_path = "../media/ecocases/"
# Create your views here.

esms = [
    "Innover par la création de valeur en prenant en compte l'ensemble des parties prenantes",
    'Innover par le biomimétisme',
    'Innover par la prise en compte des éco-usages et les utilisateurs finaux',
    "Innover par les services et l'économie de fonctionnalité",
    'Innover par de nouveaux modes de financement',
    'Innover par le bouclage de flux (matières, informations…)  et les circuits courts',
    'Innover par les matériaux et production',
    "Innover par la gestion du transfert d'impact et l'effet rebond"
]


class IndexView(generic.ListView):
    '''
        Display five lastest ecocases by pub_date.
    '''
    template_name = 'ecocases/index.html'
    context_object_name = 'ecocase_list'

    def get_queryset(self):
        """Return the last five added ecocase. """
        return EcoCase.objects.order_by('-timestamp')


class DetailView(generic.DetailView):
    '''
        Display ecocase by id
    '''
    model = EcoCase
    template_name = 'ecocases/detail.html'


class CreateView(FormUserNeededMixin, FormView):
    form_class = EcoCaseForm
    template_name = 'ecocases/create.html'
    success_url = reverse_lazy('ecocases:index')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        images = request.FILES.getlist('images')

        if form.is_valid():
            image_url_list = []

            for count, image in enumerate(images):
                uploaded_image = ecocase_image_fs.save(image.name, image)
                image_url_list.append(uploaded_image_path + uploaded_image)

            ecocase = EcoCase(title=form.cleaned_data['title'],
                              promise=form.cleaned_data['promise'],
                              usage=form.cleaned_data['usage'],
                              organization=form.cleaned_data['organization'],
                              economic_transaction=form.cleaned_data['economic_transaction'],
                              reference=form.cleaned_data['reference'],
                              direct_environmental_gain=form.cleaned_data['direct_environmental_gain'],
                              indirect_environmental_gain=form.cleaned_data['indirect_environmental_gain'],
                              proven_cas_or_project=form.cleaned_data['proven_cas_or_project'],
                              image_urls=';'.join(image_url_list),
                              timestamp=datetime.datetime.now(),
                              user=request.user,
                              )
            ecocase.save()

            for key, value in esm_dict.items():
                ecocase.esm_set.create(
                    type=key,
                )

            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class UpdateView(UserOwnerMixin, generic.UpdateView):
    queryset = EcoCase.objects.all()
    form_class = EcoCaseForm
    template_name = 'ecocases/update.html'
    # success_url = reverse_lazy('ecocases:index')

    def get_success_url(self, **kwargs):
        return self.object.get_absolute_url()

    def form_valid(self, form):
        self.object = form.save(commit=False)
        images = self.request.FILES.getlist('images')

        image_url_list = []
        for count, image in enumerate(images):
            print('image name: ', image.name)
            uploaded_image = ecocase_image_fs.save(image.name, image)
            image_url_list.append(uploaded_image_path + uploaded_image)

        self.object.image_urls = self.object.image_urls + \
            ';' + ';'.join(image_url_list)

        self.object.save()
        return HttpResponseRedirect(self.object.get_absolute_url())

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(UpdateView, self).dispatch(request, *args, **kwargs)


class DeleteView(generic.DeleteView):
    model = EcoCase
    template_name = 'ecocases/confirm_delete.html'
    success_url = reverse_lazy('ecocases:index')


def vote(request, id):
    ecocase = get_object_or_404(EcoCase, pk=id)
    user = request.user
    if(request.POST.get('vote_button')):
        if request.user.id != None:
            print("user:", request.user.id)
            for esm in ecocase.esm_set.all():
                votes = Vote.objects.filter(esm=esm, user=user)
                vote_point = int(request.POST.get(
                    'dropdown' + str(esm.id)))
                if votes.count() == 0:
                    esm.vote_set.create(
                        user=user,
                        vote_point=vote_point
                    )
                else:
                    vote = votes[0]
                    vote.vote_point = vote_point
                    vote.save()
                esm.save()
        return HttpResponseRedirect(reverse('ecocases:detail', args=(ecocase.id,)))
    else:
        return render(request, 'ecocases/vote.html', {
            'ecocase': ecocase,
            'error_message': "Something wrongs, please check your voting.",
        })


def profile(request, username):
    user = User.objects.get(username=username)
    ecocases = EcoCase.objects.filter(user=user)
    return render(request, 'user/profile.html',
                  {'username': username, 'ecocases': ecocases})


def login_view(request):
    form = LoginForm(request.POST or None)
    if request.POST and form.is_valid():
        user = form.login(request)
        if user:
            login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect(reverse('ecocases:profile', args=(user.username, )))
    return render(request, 'user/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('ecocases:index'))


def new_login_view(request):
    form = LoginForm(request.POST or None)
    if request.POST and form.is_valid():
        user = form.login(request)
        if user:
            login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect(reverse('ecocases:profile', args=(user.username, )))
    return render(request, 'login.html', {'form': form})


def new_logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('ecocases:index'))


def mechanism_list(request):
    return render(request, 'mechanisms/index.html', {'esm_dict': esm_dict, 'esm_link': esm_link})


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            mail_subject = 'Activate your blog account.'
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return render(request, 'registration/activation_email_sent.html')

    else:
        form = SignupForm()

    return render(request, 'signup.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return render(request, 'registration/activation_email_checked.html')
    else:
        return render(request, 'registration/activation_link_invalid.html')


def upload_csv(request):
    data = {}
    if "GET" == request.method:
        return render(request, "ecocases/upload_csv.html", data)
    # if not GET, then proceed
    try:
        csv_file = request.FILES["csv_file"]
        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'File is not CSV type')
            return HttpResponseRedirect(reverse("ecocases:upload_csv"))
        # if file is too large, return
        if csv_file.multiple_chunks():

backend/ecocases/templates/ecocases/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'registration_activate' uidb64=uid token=token %}
{% endautoescape %}

backend/ecocases/templates/ecocases/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ALIENNOR</title>
    <!-- <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}"> -->
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/superhero/bootstrap.min.css" rel="stylesheet" integrity="sha384-Xqcy5ttufkC3rBa8EdiAyA1VgOGrmel2Y+wxm4K3kI3fcjTWlDWrlnxyD6hOi3PF" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'ecocases/css/ecocases.css' %}">
    <script src="{% static "js/jquery-3.2.1.js" %}"></script>
    <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/tinymce/tinymce.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tinymce/custom.js' %}" ></script>
</head>

<body> 
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'admin:index' %}">
                    ALIENNOR Platform
                </a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'ecocases:index' %}">Ecocases</a></li>
                <li><a href="{% url 'ecocases:mechanism_list' %}">Mechanisms</a></li>
            </ul>
            {% block toggle_login %}
                {% include "toggle_login.html" %}
            {% endblock %}
        </div>
    </nav>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    {% block script %}{% endblock script %}
</body>
</html>

backend/ecocases/templates/ecocases/confirm_delete.html
{% extends "base.html" %}
{% block content %}
  <form action="" method="post">{% csrf_token %}
      <p>Are you sure you want to delete the tweet "{{ object }}"?</p>
      <div class="text-right">
          <input type="submit" class="btn btn-info" value="Confirm" />
      </div>
      
  </form>
{% endblock content %}

backend/ecocases/templates/ecocases/create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<!-- create new ecocase -->
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">Create new ecocase</h4>
        </div>
        <br>
        <div class="panel-body">
            {% include "ecocases/form.html" with form=form btn_class="btn btn-info" btn_title="Submit" %}
        </div>
    </div>
{% endblock %}

backend/ecocases/templates/ecocases/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load ecocase_extras %}

{% block content %}
<!-- Display ecocase by id -->
<div class="panel panel-default">
	<div class="panel-heading text-center"><h4>{{ ecocase.title }}</h4></div>
	<!-- <div class="panel-heading">
			<h3 class="panel-title"><a href="{% url 'ecocases:detail' ecocase.id %}">{{ ecocase.title }}</a></h3>
	</div> -->
	<div class="panel-body">
		<div class="row top-buffer">
				<div class="col-md-4">
					<div class="panel panel-default">
						<div class="panel-heading">Visualization</div>
						<div class="panel-body">
							<div class="cover-container">
								<ul class="list-inline">
									{% if ecocase.image_url_list != '' %}
										{% for image_url in ecocase.image_url_list %}
											<div class="cover-item">
												<img src="{% static image_url %}" class="center-block" alt="" height="250px">
											</div>
										{% endfor %}
									{% else %}
										<div class="cover-item">
											<img src="{% static 'ecocases/no_visualization.png' %}" class="center-block" alt="" height="250px">
										</div>
									{% endif %}
									
								</ul>           
							</div>  
						</div>
					</div>					          
				</div>					
				<div class="col-md-8 characters-area">
					<div class="panel panel-default">
						<div class="panel-heading">Promise</div>
						<div class="panel-body">
							{% autoescape off %}{{ ecocase.promise }}{% endautoescape %}
						</div>
					</div>
					<div class="panel panel-default">
						<div class="panel-heading">Usage</div>
						<div class="panel-body">
							{% autoescape off %}{{ ecocase.usage }}{% endautoescape %}
						</div>
					</div>
					<div class="panel panel-default">
						<div class="panel-heading">Organization</div>
						<div class="panel-body">
							{% autoescape off %}{{ ecocase.organization }}{% endautoescape %}
						</div>
					</div>
					<div class="panel panel-default">
						<div class="panel-heading">Economic transaction</div>
						<div class="panel-body">
							{% autoescape off %}{{ ecocase.economic_transaction }}{% endautoescape %}
						</div>
					</div>
				</div>
		</div>
		<div class="row">
			<div class="col-md-6 evaluation-div">
				<div class="panel panel-default">
					<div class="panel-heading">Evaluation</div>
					<div class="panel-body">
						<div class="row">
								<div class="col-md-8">Reference</div>
								<div class="col-md-4">{{ ecocase.reference }}</div>
						</div>
						<div class="row">
								<div class="col-md-8">Direct environmental gain</div>
								<div class="col-md-4">{{ ecocase.direct_environmental_gain }}</div>
						</div>
						<div class="row">
								<div class="col-md-8">Indirect environmental gain</div>
								<div class="col-md-4">{{ ecocase.indirect_environmental_gain }}</div>
						</div>
						<div class="row">
								<div class="col-md-8">Provent cas or projet/ Price</div>
								<div class="col-md-4">{{ ecocase.proven_cas_or_project }}</div>
						</div>
						<div class="row">
								<div class="col-md-8">Attractiveness/ Price</div>
								<div class="col-md-4">{{ ecocase.attractiveness_price }}</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-6 evaluation-div">
				<div class="panel panel-default">
					<div class="panel-heading">Revelant mechanisms</div>
					<div class="panel-body">
						<div class="row">
								<div class="col-md-6">Main route</div>
								<div class="col-md-6">{{ ecocase.reference }}</div>
						</div>
						<div class="row">
								<div class="col-md-6">Secondary route</div>
								<div class="col-md-6">{{ ecocase.direct_environmental_gain }}</div>
						</div>	
					</div>
				</div>
			</div>
		</div>
		<hr>
		<div class="panel panel-default">
			<div class="panel-heading">Associated mechanisms</div>	
			<div class="panel-body">
				{% if ecocase.esm_set.all %}
					{% for esm in ecocase.esm_set.all %}
							<div class="row top-buffer">
									<div class="col-md-8">	
										{{ esm.get_title }}						
									</div>
									<div class="col-md-4 text-right">
										{{ esm.get_vote_point_total }} vote{{ esm.get_vote_point_total|pluralize }}
									</div>
							</div>
					{% endfor %}
				{% endif %}
			</div>
		</div>		      		
	</div>  
</div>
<div class="text-right">
		<button type="button" class="btn btn-primary"><a href="{% url 'ecocases:index' %}">Back to list</a></button>
		{% if ecocase.user == request.user %}
			<button type="button" class="btn btn-default"><a href="{% url 'ecocases:update' ecocase.id %}">Update</a></button>
			<button type="button" class="btn btn-danger"><a href="{% url 'ecocases:delete' ecocase.id %}">Delete</a></button>
		{% endif %}
		{% if request.user.id == None %}
			<button type="button" class="btn btn-success"><a href="{% url 'mysite_login' %}">Login to vote</a></button>	
		{% elif ecocase|is_voted:request.user.id %}
			<button type="button" class="btn btn-success"><a href="{% url 'ecocases:vote' ecocase.id %}">Vote again?</a></button>
		{% else %}
			<button type="button" class="btn btn-success"><a href="{% url 'ecocases:vote' ecocase.id %}">Vote</a></button>
		{% endif %}
</div>
{% endblock %}

backend/ecocases/templates/ecocases/form.html
{% load crispy_forms_tags %}
<form {% if form_id %} id={{ form_id }} {% endif %} class='form' action="{% if action_url %}{{ action_url }}{% endif %}" method="post" enctype="multipart/form-data" multiple> {% csrf_token %}
    {{ form|crispy }}      
    <div class="text-right">
        <input type="submit" class="{{ btn_class }}" value="{{ btn_title }}" class=""/>
    </div>
</form>

backend/ecocases/templates/ecocases/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}

{% block toggle_login %}{% endblock %}

{% block heading %}
  <h2>Login</h2>
{% endblock %}

{% block content %}
  <form action="{% url "mysite_login" %}" method="post" accept-charset="utf-8">
    {{ form|crispy }}
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    <input class="btn btn-default" type="submit" value="Login">
  </form>
{% endblock %}

backend/ecocases/templates/ecocases/toggle_login.html
{% if user.is_authenticated %}
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
        aria-expanded="false">{{ user.username }}<span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><a href="{% url "mysite_logout" %}">Logout</a></li>
    </ul>
  </li>
</ul>
{% else %}
<ul class="nav navbar-nav navbar-right">
  <button type="submit" class="btn btn-warning pull-right"><a href="{% url 'mysite_signup' %}">Sign up</a></button>
  <button type="submit" class="btn btn-success pull-right"><a href="{% url 'mysite_login' %}">Login in</a></button>
</ul>
{% endif %}

backend/ecocases/templates/ecocases/upload_json.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<form action="{% url 'ecocases:upload_json' %}" method="POST" enctype="multipart/form-data" class="form-horizontal"> 
    {% csrf_token %}
    <div class="form-group">
        <label for="name" class="col-md-2 col-sm-2 col-xs-12 control-label">File: </label>
        <div class="col-md-6">
            <input type="file" name="json_file" id="json_file" required="True" class="form-control">
        </div> 
        <div class="col-md-2">
            <button class="btn btn-success btn-sm"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
        </div>                    
    </div>
</form>
</div>

{% endblock %}

backend/ecocases/templates/ecocases/vote.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load ecocase_extras %}

{% block content %}
	<div class="panel panel-default">
		<div class="panel-heading"><h4>{{ ecocase.title }}</h4></div>
		<div class="panel-body">
			<form action="{% url 'ecocases:vote' ecocase.id %}" method="post">
				{% csrf_token %} 
				{% for esm in ecocase.esm_set.all %}
					<select name="dropdown{{ esm.id }}" id="esm{{ forloop.counter }}">
						{% for i in esm.vote_point_options %}
							{% if i == esm|get_vote_point_by_user:request.user.id %}
								<option value="{{ i }}" selected>{{ i }}</option>		
							{% else %}
								<option value="{{ i }}">{{ i }}</option>		
							{% endif %}						
						{% endfor %}		
					</select>
					<!-- <input type="radio" name="esm" id="esm{{ forloop.counter }}" value="{{ esm.id }}" /> -->
					<label for="esm{{ forloop.counter }}">{{ esm.id }}{{ esm.get_title }}</label><br /> 
				{% endfor %}
				<hr>
				{{ post_request }}
				<div class="text-right">
					<input type="submit" class="btn btn-success btn-sm" name="vote_button" value="Vote" />
				</div>
			</form>
		</div>
	</div>
{% endblock content %}

backend/ecocases/templates/ecocases/vote2.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="panel panel-default">
	<div class="panel-heading"><h4>{{ ecocase.title }}</h4></div>
	<div class="panel-body">
		<form action="{% url 'ecocases:vote' ecocase.id %}" method="post">
			{% csrf_token %} 
			{% for esm in ecocase.esm_set.all %}
				<input type="radio" name="esm" id="esm{{ forloop.counter }}" value="{{ esm.id }}" />
				<label for="esm{{ forloop.counter }}">{{ esm.get_title }}</label><br /> 
			{% endfor %}
			{% if messages %}
			{% for message in messages %}
				<div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
			{% endfor %}
			{% endif %}
			{% if error_message %}
			<p><strong>{{ error_message }}</strong></p>{% endif %}
			<hr>
			<div class="text-right">
				<input type="submit" class="btn btn-success btn-sm" value="Vote" />
			</div>
		</form>
	</div>
</div>
{% endblock content %}